services:
  frost-server:
    image: fraunhoferiosb/frost-server-http:latest
    # image: fraunhoferiosb/frost-server:latest
    environment:
      # For all settings see: https://fraunhoferiosb.github.io/FROST-Server/settings/settings.html
      - serviceRootUrl=http://localhost:8080/FROST-Server
      - plugins_multiDatastream.enable=false
      - http_cors_enable=true
      - http_cors_allowed_origins=*
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://frost-db:5432/sensorthings
      - persistence_db_username=sensorthings
      - persistence_db_password=ChangeMe
      - persistence_autoUpdateDatabase=true
    ports:
      - 8080:8080
      # - 1883:1883
    depends_on:
      frost-db:
        condition: service_healthy

  frost-db:
    image: postgis/postgis:14-3.2-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=ChangeMe
    volumes:
      - postgis_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d sensorthings -U sensorthings "]
      interval: 10s
      timeout: 5s
      retries: 5
  
  grafana-dashboard:
    image: grafana/grafana:latest
    ports:
     - 3000:3000

  dash-dashboard:
    image: frost_dash:latest
    ports:
     - 8050:8080
    environment:
      - URL=http://frost-server
      - PORT=8080
    depends_on:
      frost-server: 
        condition: service_started

volumes:
    postgis_volume: 

